name: project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.*
  - numpy=1.24.*
  - pandas=2.0.*
  - pip=23.3.*
  - scikit-learn=1.3.*
  - openpyxl=3.1.2
  - pytest=7.4.0
  - pytest-mock=3.12.0
  - hydra-core
  - requests=2.31.0
  - dvc=3.33.0
  - pip:
      - wandb==0.16.*
      - mlflow[extras]==2.9.*
